# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xinxinLove' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xinxinLove

  target 'xinxinLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xinxinLoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'Masonry'


end
